import Head from 'next/head';
import { useState } from 'react';
import Articles from './components/Articles';
import Sources from './components/Sources';

export const getStaticProps = async () => {
  const res = await fetch(
    "https://newsapi.org/v2/everything?q=apple&from=2021-09-21&to=2021-09-21&sortBy=popularity&apiKey=0cb60059c1974e85a3b1b8ef1d36036b"
  );
  const data = await res.json();

  return {props: {data}}
}


export default function Home({ data }) {

  
  const [articles, setArticles] = useState(data.articles);

  //getting the unique values
  const sortedSources = ["All", ...new Set(articles.map((item) => item.source.name)),];

  //to stop changing the buttons
  // const [sortedSources, setSortedSources] = useState(sorted_Sources)

  
  //filtering based on the unique values
  const filteredSources = (source) => {
    if (source === 'All') {
      return setArticles(data.articles)
    }

    const newSource = articles.filter(item => item.source.name === source)
    setArticles(newSource)
    // setSortedSources(sorted_Sources)
  }

  return (
    <div >
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className='flex h-full'>
        <Sources  sortedSources={sortedSources} filteredSources={filteredSources} />
        <Articles articles={articles} />
      </main>

    </div>
      
  )
}
